### ISSUE TITLE
Proposal: Somehow tagging the blog posts w/ language(s) used (🐍Ⓡ?)

### ISSUE THREAD

**Issue by batpigandme** [h2oai/awesome-h2o#5]
Most of them have the language in their titles, but some don't. Just a thought…

**Comment by ledell** [comment]
This is a nice idea, but I am not a fan of the emojis (especially the R emoji).  I made an attempt to try to use an inline-image (using favicons for R and Python foundation websites), what do you think?

- Example blog post title in R. Nov 3, 2017  [<img src="https://www.r-project.org//favicon-16x16.png" align="right" width=18>](https://www.r-project.org//favicon-16x16.png)
- Another blog post title in Python.  Nov 3, 2017 [<img src="https://www.python.org/static/favicon.ico" align="right" width=16>](https://www.python.org/static/favicon.ico)

**Comment by batpigandme** [comment]
💖!!! Love it (in case a sparkling heart didn't convey that appropriately). My emoji thought was just for it to be quick to scan visually, and this does that, but better!
🏆👯💥

**Comment by ledell** [comment]
Do you like this better?

- Example blog post title in R. Nov 3, 2017  [<img src="https://www.r-project.org//favicon-16x16.png" width=18>](https://www.r-project.org//favicon-16x16.png)
- Another blog post title in Python.  Nov 3, 2017 [<img src="https://www.python.org/static/favicon.ico"  width=16>](https://www.python.org/static/favicon.ico)

Or this?

- [<img src="https://www.r-project.org//favicon-16x16.png" width=18>](https://www.r-project.org//favicon-16x16.png) Example blog post title in R. Nov 3, 2017
- [<img src="https://www.python.org/static/favicon.ico"  width=16>](https://www.python.org/static/favicon.ico) Another blog post title in Python.  Nov 3, 2017

**Comment by batpigandme** [comment]
I'm with you on the first, especially since so many posts contain the language anyhow— I think _visually_ it provides a better kind of browsing outside of the post titles (which makes more sense, to me, at the end of a line). So ➕1 for sure!

**Comment by ledell** [comment]
@batpigandme by "end of a line" you mean this version, where they are right-aligned?  Or do you mean at the end of the post title & date?

- Example blog post title in R. Nov 3, 2017  [<img src="https://www.r-project.org//favicon-16x16.png" align="right" width=18>](https://www.r-project.org//favicon-16x16.png)
- Another blog post title in Python.  Nov 3, 2017 [<img src="https://www.python.org/static/favicon.ico" align="right" width=16>](https://www.python.org/static/favicon.ico)

**Comment by batpigandme** [comment]
Oh, sorry, that was totally unclear— I meant the first option that you had (the end of the post title & date)
